services:
  backend:
    build:
      target: be-dev
      dockerfile: docker/local/dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=settings.local
      - PYTHONPATH=/app/src
    command: uv run python manage.py runserver

  frontend:
    build:
      target: fe-dev
      dockerfile: docker/local/dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: pnpm run dev
