services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.prod
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./manage.py:/app/manage.py
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - /app/__pycache__
      - /app/.venv-docker
    environment:
      - DEBUG=0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/project_template
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=settings.prod
    command: uv run python manage.py runserver

  frontend:
    build:
      context: .
      dockerfile: dockerfile.prod
      target: fe-prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
