# Generated by Django 5.2.5 on 2025-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(default='New Conversation', max_length=200),
        ),
    ]
