# Generated by Django 5.2.5 on 2025-09-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_llm', '0002_chatconversation_title'),
    ]

    operations = [
    ]
