# Generated by Django 5.2.5 on 2025-10-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_llm', '0004_pdfdocument_quiz_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='pdf_document',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
